version: 2.1
jobs:
 setup:
   docker:
     - image: cimg/ruby:3.2.2
   steps:
     - run:
         name: Check Ruby Version
         command: ruby -v
 test:
   docker:
     - image: cimg/ruby:3.2.2
   steps:
     - run:
         name: Run Test
         command: |
           cd test/
           ruby test.rb
workflows:
 run:
   jobs:
     - setup
     - test
