version: 2.1
jobs:
 dependency:
   docker: 
     - image: cimg/ruby:3.2.2
   steps:
     - checkout  
     - run:
          name: Install dependency
          command: bundle install   
 setup:
   docker:
     - image: cimg/ruby:3.2.2
   steps:
     - checkout
     - run:
         name: Check Ruby Version
         command: ruby -v
 test:
   docker:
     - image: cimg/ruby:3.2.2
   steps:
     - checkout
     - run:
         name: Run Test
         command: |
           ruby ./test/test.rb
 linter:
   docker:
    - image: cimg/ruby:3.2.2
   steps:
    - run:
        name: Lint code
        command:
           rubocop -a            
workflows:
 run:
   jobs:
     - setup
     - dependency
     - test
